### ISSUE TITLE
template url-key starts with app/ folder?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [ericclemmons/grunt-angular-templates#122]
Just curious, I'm serving my app out of app/ like a normal angular project.
When I run grunt to create the ngtemplates file, i see it creates they cache url-keys with 'app/' added which means they never get served when i see requests from my index.html for 'views/templates/textarea.html' when the file has the key 'app/views/templates/textarea.html'. 
I added a option for stripping app/ out of the cache key and it works, but just thought I'd ask if there is a better way to do this (by default i would assume it would work out of the app/ directory so thought I'd post here to see if its a bug or just a bad grunt setup I have).

ngtemplates: {
      screenerApp: {
        src: ["<%= yeoman.app %>/views/*.html", "<%= yeoman.app %>/views/templates/**/*.html"],
        dest: ".tmp/views/templates/cached-templates.js",
        //base : 'app/'
        options:  {
          url:    function(url) { return url.replace('app/', ''); }
        }
      }
    }
  });

The base option didn't work for me either. But either way thought it would work without extra config since its a standard angular project setup in terms of folder structure i think.

Thanks,
Ari

**Comment by windmaomao** [comment]
i have the same issue, you can use instead

    ngtemplates: {
        app: {
            cwd: '<%= yeoman.app %>',
            src: "scripts/**/*.html",
            dest: ".tmp/scripts/templates.js"
        }
    },

**Comment by armyofda12mnkeys** [comment]
thanks windmaomao, that worked for me
