### ISSUE TITLE
Looking for Contributors / Owners

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/grunt-angular-templates#137]
First, I apologize that I can't spend any time on this project.

I haven't used Grunt since I switched to Gulp, and I stopped using _that_ nearly 2 years ago.

Plus, I have a family and a full-time job, so I'm not _really_ apologizing ;)

Therefore, **respond to this thread with the following info for Github & NPM publishing rights**:

1. Github username (well, it'll be on the issue, but just to show you're serious :D)
2. NPM email / user so I can give you `npm publisher` access.

If no one steps up, I'll mark this project as deprecated and let the community find alternatives.

**Comment by underscorebrody** [comment]
1. underscorebrody
2. ebrody@gmail.com / underscorebrody

**Comment by hvdb** [comment]
Hvdb
Henkvandenbrink@gmail.Com / hvdb

**Comment by hvdb** [comment]
We are using it at our company so i have enough time to help. And we need it :)

**Comment by aaani** [comment]
1. aaani
2. anidps@gmail.com/aaani

**Comment by ericclemmons** [comment]
I seriously can't thank you guys enough! :')  I wish I did this months (years?) ago. :tada: 

```
  npm owner ls
aaani <anidps@gmail.com>
ericclemmons <eric@smarterspam.com>
hvdb <henkvandenbrink@gmail.com>
underscorebrody <ebrody@gmail.com>
```

If there's any stewardship you guys need, I'm still around.  I just can't commit the time to fully dedicate time to code, architecture, and keeping up with the ecosystem.

Thanks again!
