### ISSUE TITLE
Please update html-minifier to >= 1.0.0

### ISSUE THREAD

**Issue by plynchnlm** [ericclemmons/grunt-angular-templates#140]
Currently this package depends on html-minifier 0.6.3, which depends on a [vulnerable](https://nodesecurity.io/advisories/48) version of uglify-js.  Update to 1.0.0 or later to avoid that vulnerability.

**Comment by underscorebrody** [comment]
This was fixed via https://github.com/ericclemmons/grunt-angular-templates/pull/143, we now require `~1.1.1`
