### ISSUE TITLE
Line breaks in attributes

### ISSUE THREAD

**Issue by karensg** [ericclemmons/grunt-angular-templates#144]
Hi,

Version 0.6 and 1.0.1 have some unexpected behavior for line breaks in attributes.
Try the following:
```html
<textarea placeholder="Line1
Line2"></textarea>
```
The output of the 0.5.9 and 0.6 is different. In version 0.6, the string of the first line is only closed on a new line which breaks the integration with ngAnnotate.

Btw: thanks for updating dependencies in 1.0. Very happy about it!

Karens

**Comment by subhash85** [comment]
Yes, i have also faced the issue starting from version 0.6.0

**Comment by underscorebrody** [comment]
Thanks for reporting this, and sorry for the trouble! I'll take a look this
morning.

**Comment by underscorebrody** [comment]
@karensg or @subhash85 I'm trying to track down this issue, but running what you pasted above is giving identical results between 0.5.9 and 0.6 / 1.0. Can you provide additional detail about what's different in your results between the two version, and any additional options that might effect the output? Thanks!

**Comment by karensg** [comment]
Yes, of course.
```
ngtemplates: {
      dist: {
        options: {
          module: 'pluggdApp',
          htmlmin: '<%= htmlmin.dist.options %>',
          usemin: 'scripts/scripts.js'
        },
        cwd: '<%= yeoman.app %>',
        src: 'views/{,**/}*.html',
        dest: '.tmp/templateCache.js'
      }
    }
```
HTMLmin options:
```
options: {
          collapseWhitespace: true,
          conservativeCollapse: true,
          collapseBooleanAttributes: true,
          removeCommentsFromCDATA: true,
          removeComments: true
        }
```
HTML that fails:
```html
<textarea class="form-control form-area" maxlength="5000" name="bio" ng-model="artist.bio" ng-required="true" placeholder="Vertel de bezoeker je verhaal en wat jouw optreden uniek maakt.
Let op: verwijzingen naar andere websites of pagina's op sociale media worden verwijderd." tabindex="5"></textarea>
```

**Comment by underscorebrody** [comment]
@karensg can you also provide the correct result that you're seeing from 0.5.9 and indicate what 0.6.0 is doing wrong? Sorry for all the questions, but i'm having a hard time getting the two versions to produce different results. Thanks!

**Comment by karensg** [comment]
Thanks for looking at the issue.
This is 0.6:
```
  $templateCache.put('views/artist/steps/_1.html',
    "<textarea class=\"form-control form-area\" maxlength=\"5000\" name=\"bio\" ng-model=\"artist.bio\" ng-required=\"true\" placeholder=\"Vertel de bezoeker je verhaal en wat jouw optreden uniek maakt.
" +
    "\n" +
    "Let op: verwijzingen naar andere websites of pagina's op sociale media worden verwijderd.\" tabindex=\"5\"></textarea>"
  );
```
This is 0.5.9
```
$templateCache.put('views/artist/steps/_1.html',
    "<textarea class=\"form-control form-area\" maxlength=\"5000\" name=\"bio\" ng-model=\"artist.bio\" ng-required=\"true\" placeholder=\"Vertel de bezoeker je verhaal en wat jouw optreden uniek maakt.\r" +
    "\n" +
    "Let op: verwijzingen naar andere websites of pagina's op sociale media worden verwijderd.\" tabindex=\"5\"></textarea>"
  );
```

**Comment by underscorebrody** [comment]
Oooh, interesting. It looks like it's the `\r` that's causing the problem, we aren't handling those. I'll put together something.

**Comment by underscorebrody** [comment]
@karensg Have a look at https://github.com/ericclemmons/grunt-angular-templates/pull/147 see if that fixes it for you

**Comment by karensg** [comment]
Yes, it fixes the problem. Thanks a lot.
