### ISSUE TITLE
Regex containing "/" (backslash) fails starting from v0.6

### ISSUE THREAD

**Issue by RonaldTreur** [ericclemmons/grunt-angular-templates#145]
Hi guys,

Happy to see this project continues with a new crew. Thanks you guys and good luck! And of course a big thanks to @ericclemmons for initiating this project!

As for my issue:

I used to work with 0.5.9 and that worked great. Today I finally got around to update to v1.0.1, but unfortunately that didn't produce the same result. A regular expression contained in the HTML (ng-pattern attribute) suddenly caused the browser to throw up. I backtracked a bit and noticed this started with v0.6.

This is the regex in the source HTML file:
```javascript
/^(((\+[1-9][0-9])|(00[1-9][0-9]))[0-9]{7,11})|((((01|02|03|04|05|07|08)[0-9])|(06[1-9]))[0-9]{7})$/
```

This is what v0.5.9 produced (inside the $templateCache.put)
```javascript
/^(((\\+[1-9][0-9])|(00[1-9][0-9]))[0-9]{7,11})|((((01|02|03|04|05|07|08)[0-9])|(06[1-9]))[0-9]{7})$/
```

This is what v0.6.0 (and higher) produces (inside the $templateCache.put)
```javascript
/^(((\+[1-9][0-9])|(00[1-9][0-9]))[0-9]{7,11})|((((01|02|03|04|05|07|08)[0-9])|(06[1-9]))[0-9]{7})$/
```

The only difference is the backslash character (@ position 6) is no longer being escaped properly. Which means the end result is (in the DOM):
```javascript
/^(((+[1-9][0-9])|(00[1-9][0-9]))[0-9]{7,11})|((((01|02|03|04|05|07|08)[0-9])|(06[1-9]))[0-9]{7})$/
```
which (correctly) results in the following error:
```
SyntaxError: Invalid regular expression: /^(((+[1-9][0-9])|(00[1-9][0-9]))[0-9]{7,11})|((((01|02|03|04|05|07|08)[0-9])|(06[1-9]))[0-9]{7})$/: Nothing to repeat
    at new RegExp (native)
```

Any idea where this went wrong? When I have more time I can try to figure it out myself, but for the moment I'm back at v0.5.9.

**Comment by underscorebrody** [comment]
Thanks for the report! I have an idea where the problem might be, we modified the way we stringify the lines and it looks like something in there is causing a problem in this case. I'll take a look at it now.

**Comment by underscorebrody** [comment]
@RonaldTreur mind taking a quick look at https://github.com/ericclemmons/grunt-angular-templates/pull/146 ?

**Comment by RonaldTreur** [comment]
Tested it and works like a charm! Good to go ;-)

**Comment by evilaliv3** [comment]
i'm having the same issue but in a different context.

the current stringify function fails in case a user uses in its code escaped quotes.

this happens for example if in your code you have something like:

```html
<input name="password" class="form-control" data-ng-model="admin_password" type="password" data-ng-attr-placeholder="{{'Enter a password for the user \'admin\'' | translate}}" required>
```

i've already tried using:

```js
    options: {
      quotes: 'single'
    }
```

but obviously in this context both single and double quotes are used so switching is making other things failing.

my suggestion is in the meantime to simply revert https://github.com/ericclemmons/grunt-angular-templates/commit/d2dc35c614e5a150145cb56107c7537e12068d5a and then iterate on this issue until a stable solution is found.

**Comment by evilaliv3** [comment]
I took care to retest the fix in https://github.com/ericclemmons/grunt-angular-templates/pull/146 on GlobaLeaks that is using grunt-angular-templates extensively but some pages are still failing.

I will keep you posted with the details to be reused in the unit testing.

**Comment by underscorebrody** [comment]
@evilaliv3 What do you think about https://github.com/ericclemmons/grunt-angular-templates/pull/148 ?

**Comment by evilaliv3** [comment]
going to try it now
