### ISSUE TITLE
Better feedback when angular-templates get stuck

### ISSUE THREAD

**Issue by eduardoinnorway** [ericclemmons/grunt-angular-templates#155]
Relates to this closed issue: https://github.com/ericclemmons/grunt-angular-templates/issues/112

Please add better output information of what is happening. Now it is impossible to debugg.

**Comment by underscorebrody** [comment]
@eduardoinnorway see my comment on #112 , we are outputting everything we have control over, but the hang occurs inside of `html-minifier` so we aren't able to provide more detail. Using `--verbose` along with https://github.com/praveenvijayan/grunt-html-validation or https://github.com/htmllint/grunt-htmllint should help you track down the problem.
