### ISSUE TITLE
Standalone documentation is backwards in readme

### ISSUE THREAD

**Issue by melcher** [ericclemmons/grunt-angular-templates#75]
The explanation in the readme is currently the opposite of how the code works (which is very confusing!). It reads:

```
If the value is true, the module will look like angular.module('app'), meaning app module is retrieved.
If the value is false, the module will look like angular.module('app', []), meaning app module is created.
```

This is saying that if the templates are standalone they will retrieve an existing app. If the templates are not standalone (default) they will create a new angular app.
They should read:

```
If the value is true, the module will look like angular.module('app', []), meaning app module is created.
If the value is false, the module will look like angular.module('app'), meaning app module is retreived.
```

**Comment by LoganBarnett** [comment]
The documentation presently reads as
> If the value is false, the module will look like angular.module('app'), meaning app module is retrieved.
> If the value is true, the module will look like angular.module('app', []), meaning app module is created.

This should be safe to close.

**Comment by underscorebrody** [comment]
Yes this was resolved by https://github.com/ericclemmons/grunt-angular-templates/pull/83
